### ISSUE TITLE
Desire to read book in EPUB format

### ISSUE THREAD

**Issue by SuperSonicHub1** [llsoftsec/llsoftsecbook#211]
Thoughts from MacFarlane on how to do so with Pandoc: https://pandoc.org/epub.html

**Comment by kbeyls** [comment]
For now, we produce HTML and PDF. I'm assuming by raising this issue you'd like to indicate that there is at least one reader with an interest to read in epub format ;) ? Thank you for raising the issue - otherwise I may not have known there is an interest in the epub format.

I'm not a user of the epub format myself, so any guidance on how to best create epubs, beyond the link you shared above, is very much appreciated.

We have done a number of customizations to both the HTML and the PDF output to make the book nicer to read. I guess we should investigate if we'd need to do similar customizations to epub output.

**Comment by SuperSonicHub1** [comment]
Yeah, this issue was a bit poorly worded as I was in a rush to get out the door.
I want to use EPUB as it makes for a much better mobile offline reading experience than a PDF.
I'll see if I can get the book to compile on my PC and then begin to play around with Pandoc until I get something good.

**Comment by kbeyls** [comment]
> Yeah, this issue was a bit poorly worded as I was in a rush to get out the door. I want to use EPUB as it makes for a much better mobile offline reading experience than a PDF. I'll see if I can get the book to compile on my PC and then begin to play around with Pandoc until I get something good.

That's great. If you run into any issue building the book locally, please let me know, I'd be interested to hear about any issues you encounter. We've chosen to build by default in a docker container to avoid issues with different versions of pandoc, latex, etc, so I would hope you wouldn't encounter many issues if you make use of the `build_with_docker.sh` or `build_with_docker.bat` scripts.

**Comment by kbeyls** [comment]
@all-contributors please add @SuperSonicHub1 for bug, ideas

**Comment by kbeyls** [comment]
This has been implemented by @rommelDB in #233, so closing this ticket.

Note that there are a range of further improvements possible, which IIRC don't have github issue tickets at the moment:

[ ] customize the cover
[ ] improve the quality of the images
[ ] styling with CSS
[ ] Make the "TODO" items visible in a reasonable way in the epub format, like they are visible in html (on the side) and in the PDF format.
[ ] Add a button to the website to enable downloading this epub format (and also add download options for downloading the PDF and the HTML versions too)
[ ] The References section is empty in the epub format. Is that a limitation of pandoc, or is there something that could be done to improve how references work in the epub format?

**Comment by kbeyls** [comment]
https://github.com/all-contributors please add @rommelDB  for code

**Comment by kbeyls** [comment]
@all-contributors please add @rommelDB for code
