### ISSUE TITLE
Should the book be versioned?

### ISSUE THREAD

**Issue by JLouisKaplan-Arm** [llsoftsec/llsoftsecbook#63]
Unlike technical documentation, the book doesn't correspond to specific versions of a software package. However, I wonder if there might still be benefits to using a versioning system (e.g. semver) to mark 'releases' of the book.

I noticed, for example, that the 'Pro Git' e-book is versioned: https://github.com/progit/progit2

**Comment by kbeyls** [comment]
It makes a lot of sense to me to have version numbers in the book.
The most basic version number could be just recording the git hash the book was built from in the front matter of the book, e.g. near the copyright information?
Of course git hashes are not very human friendly to interpret so if we had a monotonically increasing number for every commit, that probably would be nicer?
I'm thinking that having a version number for each commit is useful as we are publishing the book live at llsoftsec.github.io/llsoftsecbook/, so every commit gets "published" as a version.

With semver, I'm assuming you refer to https://semver.org/?
I'm not sure exactly how to map the main rules (copied below) to a book:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
>     MAJOR version when you make incompatible API changes,
>     MINOR version when you add functionality in a backwards compatible manner, and
>     PATCH version when you make backwards compatible bug fixes.
> 
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

The book doesn't have an API, so it's unclear how to map the "MAJOR" version rule to the book? Maybe doing a major restructuring of the book could be interpreted as "incompatible API change"?
Maybe it makes more sense for the version number to start with "0.*" while we think the book has major missing content; and move it to "1.*" when we believe most or all necessary areas are covered?

I'm assuming we'd update the "MINOR" version every time we add content, as that in my mind maps to "add functionality in a backwards compatible manner".
In practice, unless we implement some smart script that detects if a commit actually changes any content in the book, I'm assuming we'd just increment the "MINOR" version with any commit in some automated way?

For "PATCH" version, I'm assuming if we use a simple automated approach to increase the "MINOR" version, we'd probably never use the "PATCH" version?

Does the above scheme look like a good approach to add version numbers to the book?
If so, I think someone should investigate how to automatically compute the version number in a script, based purely on the information present in the git history; and insert that version number automatically when building the book.

**Comment by kbeyls** [comment]
@all-contributors please add @JLouisKaplan-Arm for bug, ideas.

**Comment by JLouisKaplan-Arm** [comment]
I think all the suggestions you made are viable and sound good to me! To add some more food-for-thought however, some variation on the calver system might be useful for us:

https://calver.org/

Commit hashes could definitely work and could be considered an implementation of sequence based identifiers:

https://en.wikipedia.org/wiki/Software_versioning#Sequence-based_identifiers

**Comment by jacobbramley** [comment]
Managing SemVer for software projects can be difficult, even when they present a quantifiable API and it's possible (in theory) to objectively determine which of MAJOR, MINOR or PATCH should be bumped. This is useful for software because as a user of a library, you get information about whether or not a given version will be compatible with your code.

Whilst it's probably possible to do that for a book (using a scheme as you describe), it's going to get fuzzy, and the different fields probably won't be that useful to end users anyway. Version numbers on e-books and online documentation are useful for keeping or giving links that won't break when things move on, and for comparing versions (to see what has changed). They're also possibly useful for labelling milestones (e.g. print runs) but that's almost an independent problem.

It seems to me that a simple incrementing integer satisfies this, and it's also very easy to apply retrospectively. (E.g. count Git commit distance from some reference.)

Note that whilst the Rust ecosystem uses SemVer extensively, its documentation (like the [Rust book](https://github.com/rust-lang/book)) does not.

**Comment by kbeyls** [comment]
@all-contributors please add @jacobbramley for ideas.

**Comment by kbeyls** [comment]
I explored this a bit further just now and created pull request #77 to implement automatically computing a version number from git metadata.
Since the above discussion highlights that we probably do not have a need for a complex versioning scheme, I thought to chose one that could be implemented easily.
See the pull request for the details; but the gist of it is: the proposed versioning scheme uses "git describe"; and the version number follows the pattern 0-"number of commits since initial commit"-"git SHA version of latest commit"-{"with local changes", if there are uncommitted changes}

**Comment by kbeyls** [comment]
After just checking the PDF and HTML build as part of github actions on pull request #77, which are available at https://github.com/llsoftsec/llsoftsecbook/suites/4737017532/artifacts/130736466, it seems that in those builds the version number isn't computed correctly. Something I'll have to go and investigate. My initial guess is that maybe in the CI builds, the tags from the repository aren't cloned along?

**Comment by kbeyls** [comment]
Indeed, it seems that the default github git clone action explicitly avoids cloning tags, see https://github.com/llsoftsec/llsoftsecbook/runs/4607910009?check_suite_focus=true#step:2:40 . Now to figure out how to make tags being cloned as well...

**Comment by kbeyls** [comment]
I've added a commit to fix the above CI issue in PR #77.
Indeed, the artifacts built by the CI run available at https://github.com/llsoftsec/llsoftsecbook/suites/4737156830/artifacts/130744174 show the following version number now: Version 0-59-g5548849.
