### ISSUE TITLE
Include brief 'plain english' description of license and copyright of book

### ISSUE THREAD

**Issue by JLouisKaplan-Arm** [llsoftsec/llsoftsecbook#67]
The book is licensed under Creative Commons and copyright belongs to Arm. Is it feasible and worthwhile to include a brief 'plain english' / non-legalese summary of what this means, particularly for people outside of Arm who might consider contributing?

**Comment by kbeyls** [comment]
Copyright does not belong to Arm per se - copyright keeps on being owned by who contributes. Or in other words, no copyright transfer happens when contributing. It happens to be the case that so far, contributors happen to all work at Arm and hence so far, all material in the book happens to be copyright owned by Arm.

Maybe it could be useful to have something in contributing.md to explain that more clearly and highlight that you should add a copyright line if your contribution is copyright owned by someone or an entity not listed yet?

For Creative Commons, maybe we could provide a pointer to some page on https://creativecommons.org/ that explains the license easily. Maybe https://creativecommons.org/licenses/by/4.0/?

**Comment by JLouisKaplan-Arm** [comment]
Thanks, that first paragraph in particular addresses the main uncertainty I had. I think it would definitely be worth including that (or something similar) in contributing.md. A link to the creative commons license in contributing.md would certainly be handy as well.

If many non-Arm people do contribute, I wonder if some variation of this is valid:
(C) Arm Ltd
(C) Contributors

Or, as you said, it may be more appropriate for each non-Arm contributor to add their name explicitly.

Apologies if I'm getting carried away thinking about things that not needed yet. but perhaps planning ahead we might reduce the risk of alienating any potential contributors.

Having a quick look at other open-source (but company-owned) projects for reference, PyTorch is an interesting example:
https://github.com/pytorch/pytorch/blob/master/LICENSE#L35

**Comment by kbeyls** [comment]
> Thanks, that first paragraph in particular addresses the main uncertainty I had. I think it would definitely be worth including that (or something similar) in contributing.md. A link to the creative commons license in contributing.md would certainly be handy as well.

I'll look into doing that.

> If many non-Arm people do contribute, I wonder if some variation of this is valid: (C) Arm Ltd (C) Contributors

There is nothing special about contributions from Arm versus not from Arm.
My thinking here has been to add explicit lines for every copyright owner.
If or when the list becomes too long, we should probably just move the list to some "contributors" file and point to that from the copyright notice.

> 
> Or, as you said, it may be more appropriate for each non-Arm contributor to add their name explicitly.
> 
> Apologies if I'm getting carried away thinking about things that not needed yet. but perhaps planning ahead we might reduce the risk of alienating any potential contributors.

No worries, this is very valuable feedback!

> 
> Having a quick look at other open-source (but company-owned) projects for reference, PyTorch is an interesting example: https://github.com/pytorch/pytorch/blob/master/LICENSE#L35

Just to make sure there isn't a misunderstanding here: this project is not a company-owned open-source project. It is true that most/all contributions so far have been done by Arm employees, but that is where the extent of a company owning this project ends.
